---
name: Term-TermKey-Async
version: 0.05
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
abstract: |-
  terminal key input using C<libtermkey> with
  C<IO::Async>
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  IO::Async: 0.21
  Term::TermKey: 0.06
configure_requires:
  Module::Build: 0.35
provides:
  Term::TermKey::Async:
    file: lib/Term/TermKey/Async.pm
    version: 0.05
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
