---
name: Term-TermKey-Async
version: 0.02
author:
  - 'Paul Evans E<lt>leonerd@leonerd.org.ukE<gt>'
abstract: 'perl wrapper around C<libtermkey> for C<IO::Async>'
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Term::TermKey: 0.03
provides:
  Term::TermKey::Async:
    file: lib/Term/TermKey/Async.pm
    version: 0.02
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
